import { useState, useEffect } from "react";

// Function that returns the POD options array
export const getPODOptions = () => {
  return [
    "Abidjan, Ivory Coast",
    "Abu Dhabi Port, UAE",
    "Aden, Yemen",
    "Adelaide Port, Australia",
    "Alexandria, Egypt",
    "Algeciras, Spain",
    "Al Maqal, Iraq",
    "Altamira Port, Mexico",
    "Antofagasta Port, Chile",
    "Antwerp, Belgium",
    "Antwerp-Bruges, Belgium",
    "Auckland, New Zealand",
    "Bahía Blanca Port, Argentina",
    "Bangkok Port, Thailand",
    "Bandar Abbas Port, Iran",
    "Bandar-e Anzali, Iran",
    "Banjul, Gambia",
    "Barcelona, Spain",
    "Barranquilla Port, Colombia",
    "Beira, Mozambique",
    "Belawan Port, Indonesia",
    "Belize, Belize",
    "Brisbane Port, Australia",
    "Buenos Aires, Argentina",
    "Buenaventura Port, Colombia",
    "Burnie Port, Australia",
    "Busan Port, South Korea",
    "Busan, South Korea",
    "Cai Mep Port, Vietnam",
    "Cairns Port, Australia",
    "Callao Port, Peru",
    "Cam Ranh Port, Vietnam",
    "Cape Town, South Africa",
    "Cartagena Port, Colombia",
    "Casablanca, Morocco",
    "Charleston Port, USA",
    "Chennai Port, India",
    "Chittagong, Bangladesh",
    "Colombo, Sri Lanka",
    "Colonia Port, Uruguay",
    "Conakry, Guinea",
    "Dakar, Senegal",
    "Da Nang Port, Vietnam",
    "Dampier Port, Australia",
    "Dar es Salaam, Tanzania",
    "Darwin Port, Australia",
    "Djibouti, Djibouti",
    "Doha, Qatar",
    "Duqm, Oman",
    "Durban, South Africa",
    "Elizabeth, South Africa",
    "Ensenada Port, Mexico",
    "Felixstowe, United Kingdom",
    "Freeport Port, Bahamas",
    "Fremantle Port, Australia",
    "Fujairah Port, UAE",
    "Fujairah, UAE",
    "Geelong Port, Australia",
    "Genoa, Italy",
    "Geraldton Port, Australia",
    "Gladstone Port, Australia",
    "Guangzhou Port, China",
    "Guangzhou, China",
    "Guayaquil Port, Ecuador",
    "Guaymas Port, Mexico",
    "Gwangyang Port, South Korea",
    "Haifa Port, Israel",
    "Hamad, Qatar",
    "Hambantota Port, Sri Lanka",
    "Hamburg, Germany",
    "Harcourt, Nigeria",
    "Haiphong, Vietnam",
    "Hedland Port, Australia",
    "Hobart Port, Australia",
    "Ho Chi Minh City, Vietnam",
    "Hodeidah, Yemen",
    "Hong Kong Port, Hong Kong",
    "Hong Kong, Hong Kong",
    "Houston Port, USA",
    "Incheon Port, South Korea",
    "Iquique Port, Chile",
    "Itajaí Port, Brazil",
    "Jakarta (Tanjung Priok), Indonesia",
    "Jebel Ali, UAE",
    "Jeddah Islamic, Saudi Arabia",
    "Jeddah, Saudi Arabia",
    "Kaohsiung Port, Taiwan",
    "Kaohsiung, Taiwan",
    "Karachi, Pakistan",
    "Keelung Port, Taiwan",
    "Khalid, UAE",
    "Khalifa Bin Salman, Bahrain",
    "Khalifa, UAE",
    "King Abdul Aziz, Saudi Arabia",
    "King Fahad Industrial, Saudi Arabia",
    "Kingston Port, Jamaica",
    "Khor Al Zubair, Iraq",
    "Khor Fakkan, UAE",
    "Klang, Malaysia",
    "Kobe Port, Japan",
    "Kolkata Port, India",
    "La Guaira Port, Venezuela",
    "Laem Chabang, Thailand",
    "Lagos (Apapa), Nigeria",
    "Lázaro Cárdenas Port, Mexico",
    "Libreville, Gabon",
    "Lomé, Togo",
    "Long Beach, USA",
    "Los Angeles Port, USA",
    "Los Angeles, USA",
    "Luanda, Angola",
    "Map Ta Phut Port, Thailand",
    "Maputo, Mozambique",
    "Manila, Philippines",
    "Manzanillo, Mexico",
    "Matarani Port, Peru",
    "Medan Port, Indonesia",
    "Melbourne, Australia",
    "Mendoza Port, Argentina",
    "Mesaieed, Qatar",
    "Miami Port, USA",
    "Mina Saqr, UAE",
    "Mina Salman, Bahrain",
    "Mombasa, Kenya",
    "Monrovia, Liberia",
    "Montevideo Port, Uruguay",
    "Montreal, Canada",
    "Mongla Port, Bangladesh",
    "Mukalla, Yemen",
    "Mumbai Port, India",
    "Nagoya Port, Japan",
    "Nassau Port, Bahamas",
    "New Jersey (NJ), USA",
    "New York (NY), USA",
    "New York and New Jersey Port, USA",
    "Nhava Sheva (JNPT) Port, India",
    "Nha Trang Port, Vietnam",
    "Ningbo-Zhoushan Port, China",
    "Ningbo-Zhoushan, China",
    "Nouakchott, Mauritania",
    "Oakland Port, USA",
    "Osaka, Japan",
    "Paita Port, Peru",
    "Paranaguá Port, Brazil",
    "Pasir Gudang Port, Malaysia",
    "Perth Port (Fremantle), Australia",
    "Phu My Port, Vietnam",
    "Piraeus, Greece",
    "Pointe-Noire, Republic of Congo",
    "Prince Rupert Port, Canada",
    "Puerto Bolívar Port, Ecuador",
    "Puerto Cabello Port, Venezuela",
    "Puerto Cortes, Honduras",
    "Qingdao Port, China",
    "Qingdao, China",
    "Quebec City Port, Canada",
    "Quy Nhon Port, Vietnam",
    "Rashid, UAE",
    "Richards Bay, South Africa",
    "Rio de Janeiro Port, Brazil",
    "Rosario Port, Argentina",
    "Rotterdam, Netherlands",
    "Salalah, Oman",
    "Salvador Port, Brazil",
    "San Antonio Port, Chile",
    "San Juan, Puerto Rico",
    "Santos, Brazil",
    "Santo Domingo, Dominican Republic",
    "Savanah, USA",
    "Seattle Port, USA",
    "Shanghai Port, China",
    "Shanghai, China",
    "Shenzhen Port, China",
    "Shuaiba, Kuwait",
    "Shuwaikh, Kuwait",
    "Singapore Port, Singapore",
    "Singapore, Singapore",
    "Sittwe Port, Myanmar",
    "Sohar, Oman",
    "Southampton, United Kingdom",
    "Sudan Port, Sudan",
    "Sultan Qaboos, Oman",
    "Surabaya Port, Indonesia",
    "Sydney Port, Australia",
    "Sydney, Australia",
    "Takoradi, Ghana",
    "Tan Cang Port, Vietnam",
    "Tanganyika (Kalemie), DRC",
    "Tangier, Morocco",
    "Tema, Ghana",
    "Tianjin Port, China",
    "Tianjin, China",
    "Tokyo Port, Japan",
    "Tokyo, Japan",
    "Townsville Port, Australia",
    "Ulsan Port, South Korea",
    "Umm Qasr, Iraq",
    "Valencia, Spain",
    "Valparaíso Port, Chile",
    "Vancouver, Canada",
    "Veracruz Port, Mexico",
    "Virginia Port (Norfolk), USA",
    "Visakhapatnam Port, India",
    "Vung Tau Port, Vietnam",
    "Walvis Bay, Namibia",
    "Yangon Port, Myanmar",
    "Yanbu Commercial, Saudi Arabia",
    "Yokohama Port, Japan",
    "Yokohama, Japan",
    "Zayed, UAE",
  ];
};

// Function to fetch POD options from API if needed in the future
export const fetchPODOptions = async () => {
  try {
    // This function can be expanded later to fetch from an API
    // For now, returning the static list
    return getPODOptions();
  } catch (error) {
    console.error("Error fetching POD options:", error);
    return getPODOptions(); // Fallback to static list
  }
};

// React hook for consuming POD options in components
export const usePODOptions = () => {
  const [options, setOptions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const getOptions = async () => {
      try {
        const result = await fetchPODOptions();
        setOptions(result);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    getOptions();
  }, []);

  return { options, loading, error };
};

export default getPODOptions;
