import { useState, useEffect } from "react";

// Function that returns the POD options array
export const getPODOptions = () => {
  return [
    "Klang, Malaysia",
    "Alexandria, Egypt",
    "Algeciras, Spain",
    "Antwerp, Belgium",
    "Antwerp-Bruges, Belgium",
    "Auckland, New Zealand",
    "Barcelona, Spain",
    "Buenos Aires, Argentina",
    "Busan, South Korea",
    "Cape Town, South Africa",
    "Chittagong, Bangladesh",
    "Colombo, Sri Lanka",
    "Durban, South Africa",
    "Felixstowe, United Kingdom",
    "Genoa, Italy",
    "Guangzhou, China",
    "Haiphong, Vietnam",
    "Hamburg, Germany",
    "Ho Chi Minh City, Vietnam",
    "Hong Kong, Hong Kong",
    "Jakarta (Tanjung Priok), Indonesia",
    "Jebel Ali, UAE",
    "Jeddah, Saudi Arabia",
    "Kaohsiung, Taiwan",
    "Karachi, Pakistan",
    "Laem Chabang, Thailand",
    "Long Beach, USA",
    "Los Angeles, USA",
    "Manila, Philippines",
    "Manzanillo, Mexico",
    "Melbourne, Australia",
    "Montreal, Canada",
    "New York and New Jersey, USA",
    "Ningbo-Zhoushan, China",
    "Osaka, Japan",
    "Piraeus, Greece",
    "Qingdao, China",
    "Rotterdam, Netherlands",
    "Salalah, Oman",
    "Santos, Brazil",
    "Savannah, USA",
    "Shanghai, China",
    "Singapore, Singapore",
    "Southampton, United Kingdom",
    "Sydney, Australia",
    "Tanjung Pelepas, Malaysia",
    "Tianjin, China",
    "Tokyo, Japan",
    "Valencia, Spain",
    "Vancouver, Canada",
    "Yokohama, Japan",
    "Rashid, UAE",
    "Khor Fakkan, UAE",
    "Khalid, UAE",
    "Zayed, UAE",
    "Khalifa, UAE",
    "Mina Saqr, UAE",
    "Fujairah, UAE",
    "Jeddah Islamic, Saudi Arabia",
    "King Abdul Aziz, Saudi Arabia",
    "King Fahad Industrial, Saudi Arabia",
    "Yanbu Commercial, Saudi Arabia",
    "Sultan Qaboos, Oman",
    "Sohar, Oman",
    "Duqm, Oman",
    "Hamad, Qatar",
    "Doha, Qatar",
    "Mesaieed, Qatar",
    "Khalifa Bin Salman, Bahrain",
    "Mina Salman, Bahrain",
    "Shuwaikh, Kuwait",
    "Shuaiba, Kuwait",
    "Umm Qasr, Iraq",
    "Al Maqal, Iraq",
    "Khor Al Zubair, Iraq",
    "Aden, Yemen",
    "Hodeidah, Yemen",
    "Mukalla, Yemen",
    "Shanghai Port, China",
    "Ningbo-Zhoushan Port, China",
    "Shenzhen Port, China",
    "Guangzhou Port, China",
    "Qingdao Port, China",
    "Tianjin Port, China",
    "Hong Kong Port, Hong Kong",
    "Busan Port, South Korea",
    "Incheon Port, South Korea",
    "Gwangyang Port, South Korea",
    "Ulsan Port, South Korea",
    "Yokohama Port, Japan",
    "Tokyo Port, Japan",
    "Kobe Port, Japan",
    "Nagoya Port, Japan",
    "Kaohsiung Port, Taiwan",
    "Keelung Port, Taiwan",
    "Singapore Port, Singapore",
    "Pasir Gudang Port, Malaysia",
    "Bangkok Port, Thailand",
    "Map Ta Phut Port, Thailand",
    "Surabaya Port, Indonesia",
    "Belawan Port, Indonesia",
    "Medan Port, Indonesia",
    "Mongla Port, Bangladesh",
    "Hambantota Port, Sri Lanka",
    "Mumbai Port, India",
    "Nhava Sheva (JNPT) Port, India",
    "Chennai Port, India",
    "Kolkata Port, India",
    "Visakhapatnam Port, India",
    "Fujairah Port, UAE",
    "Abu Dhabi Port, UAE",
    "Bandar Abbas Port, Iran",
    "Khorramshahr Port, Iran",
    "Ashdod Port, Israel",
    "Haifa Port, Israel",
    "Bandar-e Anzali, Iran",
    "Sittwe Port, Myanmar",
    "Yangon Port, Myanmar",
    "Da Nang Port, Vietnam",
    "Cai Mep Port, Vietnam",
    "Vung Tau Port, Vietnam",
    "Quy Nhon Port, Vietnam",
    "Nha Trang Port, Vietnam",
    "Cam Ranh Port, Vietnam",
    "Phu My Port, Vietnam",
    "Tan Cang Port, Vietnam",
    "Los Angeles Port, USA",
    "New York and New Jersey Port, USA",
    "Houston Port, USA",
    "Seattle Port, USA",
    "Charleston Port, USA",
    "Virginia Port (Norfolk), USA",
    "Miami Port, USA",
    "Oakland Port, USA",
    "Halifax Port, Canada",
    "Prince Rupert Port, Canada",
    "Quebec City Port, Canada",
    "Lázaro Cárdenas Port, Mexico",
    "Veracruz Port, Mexico",
    "Ensenada Port, Mexico",
    "Altamira Port, Mexico",
    "Guaymas Port, Mexico",
    "Freeport Port, Bahamas",
    "Nassau Port, Bahamas",
    "Kingston Port, Jamaica",
    "Belize, Belize",
    "Santo Domingo, Dominican Republic",
    "Puerto Cortes, Honduras",
    "San Juan, Puerto Rico",
    "Rio de Janeiro Port, Brazil",
    "Paranaguá Port, Brazil",
    "Itajaí Port, Brazil",
    "Salvador Port, Brazil",
    "Rosario Port, Argentina",
    "Bahía Blanca Port, Argentina",
    "Valparaíso Port, Chile",
    "San Antonio Port, Chile",
    "Antofagasta Port, Chile",
    "Callao Port, Peru",
    "Matarani Port, Peru",
    "Guayaquil Port, Ecuador",
    "Barranquilla Port, Colombia",
    "Cartagena Port, Colombia",
    "Buenaventura Port, Colombia",
    "La Guaira Port, Venezuela",
    "Puerto Cabello Port, Venezuela",
    "Montevideo Port, Uruguay",
    "Colonia Port, Uruguay",
    "Puerto Bolívar Port, Ecuador",
    "Iquique Port, Chile",
    "Paita Port, Peru",
    "Mendoza Port, Argentina",
    "Elizabeth, South Africa",
    "Richards Bay, South Africa",
    "Lagos (Apapa), Nigeria",
    "Harcourt, Nigeria",
    "Tema, Ghana",
    "Abidjan, Ivory Coast",
    "Dakar, Senegal",
    "Mombasa, Kenya",
    "Dar es Salaam, Tanzania",
    "Casablanca, Morocco",
    "Tangier, Morocco",
    "Djibouti, Djibouti",
    "Lomé, Togo",
    "Luanda, Angola",
    "Walvis Bay, Namibia",
    "Maputo, Mozambique",
    "Beira, Mozambique",
    "Conakry, Guinea",
    "Monrovia, Liberia",
    "Banjul, Gambia",
    "Nouakchott, Mauritania",
    "Sudan Port, Sudan",
    "Takoradi, Ghana",
    "Pointe-Noire, Republic of Congo",
    "Libreville, Gabon",
    "Tanganyika (Kalemie), Democratic Republic of Congo",
    "Sydney Port, Australia",
    "Brisbane Port, Australia",
    "Perth Port (Fremantle), Australia",
    "Adelaide Port, Australia",
    "Hobart Port, Australia",
    "Darwin Port, Australia",
    "Newcastle Port, Australia",
    "Gladstone Port, Australia",
    "Townsville Port, Australia",
    "Geelong Port, Australia",
    "Cairns Port, Australia",
    "Hedland Port, Australia",
    "Dampier Port, Australia",
    "Geraldton Port, Australia",
    "Burnie Port, Australia",
    "Fremantle Port, Australia",
  ];
};

// Function to fetch POD options from API if needed in the future
export const fetchPODOptions = async () => {
  try {
    // This function can be expanded later to fetch from an API
    // For now, returning the static list
    return getPODOptions();
  } catch (error) {
    console.error("Error fetching POD options:", error);
    return getPODOptions(); // Fallback to static list
  }
};

// React hook for consuming POD options in components
export const usePODOptions = () => {
  const [options, setOptions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const getOptions = async () => {
      try {
        const result = await fetchPODOptions();
        setOptions(result);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    getOptions();
  }, []);

  return { options, loading, error };
};

export default getPODOptions;
